-- Tablas de negocio para la migracion del Banco XYZ

CREATE TABLE IF NOT EXISTS transacciones_procesadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana VARCHAR(20) NOT NULL,
    fecha DATE NOT NULL,
    monto DECIMAL(15,2) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    anomalia BOOLEAN DEFAULT FALSE,
    motivo_anomalia VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS reporte_transacciones_diarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana VARCHAR(20) NOT NULL,
    fecha DATE NOT NULL,
    total_debitos INT DEFAULT 0,
    total_creditos INT DEFAULT 0,
    total_monto DECIMAL(15,2) DEFAULT 0,
    cantidad_anomalias INT DEFAULT 0,
    UNIQUE(semana, fecha)
);

CREATE TABLE IF NOT EXISTS cuentas_intereses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana VARCHAR(20) NOT NULL,
    cuenta_id INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    saldo_original DECIMAL(15,2) NOT NULL,
    edad INT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    tasa_interes DECIMAL(5,2) NOT NULL,
    saldo_con_interes DECIMAL(15,2) NOT NULL,
    aceptado BOOLEAN DEFAULT TRUE,
    motivo_rechazo VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cuentas_anuales_procesadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana VARCHAR(20) NOT NULL,
    cuenta_id INT NOT NULL,
    fecha DATE NOT NULL,
    transaccion VARCHAR(50) NOT NULL,
    monto DECIMAL(15,2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    anomalia BOOLEAN DEFAULT FALSE,
    motivo_anomalia VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS estados_cuenta_anuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana VARCHAR(20) NOT NULL,
    cuenta_id INT NOT NULL,
    anio INT NOT NULL,
    total_depositos DECIMAL(15,2) DEFAULT 0,
    total_retiros DECIMAL(15,2) DEFAULT 0,
    total_compras DECIMAL(15,2) DEFAULT 0,
    total_pagos DECIMAL(15,2) DEFAULT 0,
    saldo_anual DECIMAL(15,2) DEFAULT 0,
    UNIQUE(semana, cuenta_id, anio)
);
